### ISSUE TITLE
Question regarding geometry types

### ISSUE THREAD

**Issue by heidivanparys** [IAAA-Lab/U2G#6]
The current text says:

> However, it is under consideration for the GeoPackage 1.3 specification to require to contain only geometries of the type.

Could you please add a reference to a site where this is stated (a specific issue on the GeoPackage Github space maybe?)?

**Comment by fjlopez** [comment]
Yes, https://github.com/opengeospatial/geopackage/issues/445 , and the specific statement of the change was done in this [comment]( https://github.com/opengeospatial/geopackage/issues/445#issuecomment-397460987):

> Based on feedback from John Herring, I think we need to get rid of the "is assignable" nomenclature. You can put any geometry into a GEOMETRY and otherwise you have to put what it is.

 I will add it to the documentation of the encoding rule.
